name: Create a comment on new issues

on:
  issues:
    types: [opened]

jobs:
  comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      - name: Create comment with github api
        run: |
          gh api -X -POST \
            http://api.github.com/repo/{ORGANIZATION}/{REPOSITORY}/issues/{ISSUE_NUMBER}/comments
            -f body='
            Comment from the github api
            '
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: ${{ github.event.organization.login }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
