name: My Workflow
on:
  release:
    types:
      - published
jobs:
  runs-on: ubuntu-latest
  deploy: null
  name: Deploy to Netlify
  steps:
    uses: veloii/action-netlify-deploy@v2.2.1
    with:
      NETLIFY_AUTH_TOKEN: ${{ secrets.MY_TOKEN_SECRET }}
      NETLIFY_DEPLOY_TO_PROD: true
